# Generated by Django 4.0.6 on 2022-07-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('client_org', models.CharField(max_length=200, verbose_name='Организация клиента')),
                ('account_number', models.PositiveIntegerField(verbose_name='Номер-счёт')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('service', models.CharField(max_length=200, verbose_name='Название сервиса')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
            },
        ),
    ]
